name: Build .NET Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-path:
        required: true
        type: string
      project-name:
        required: true
        type: string
      solution-file:
        required: true
        type: string
      port:
        required: true
        type: string
      run-tests:
        required: false
        type: boolean
        default: true
      push-docker-image:
        required: false
        type: boolean
        default: false
      build-migration-bundle:
        required: false
        type: boolean
        default: false
      infrastructure-project-path:
        required: false
        type: string
        default: ''

jobs:
  build:
    name: Build ${{ inputs.service-name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building ${{ inputs.service-name }}"
